multiplier:
  xp: 1.1
use:
  owner-binding: true
permission:
  give-paper: "LevellingTools.givepaper"
  reload-config: "LevellingTools.reloadconfig"
  fix: "LevellingTools.fix"
  iteminfo: "LevellingTools.iteminfo"
  clearowner: "LevellingTools.clearowner"
  setowner: "LevellingTools.setowner"
language:
  no-permission: "&7Sorry, but you don't have &cpermission &7to do that!"
  console-cannot-execute-command: "&7The console &ccannot execute &7this command."
  config-reloaded: "&7The configuration has been &creloaded&7."
  givepaper-usage: "&7Please use &c/givepaper <player> <amount>&7!"
  givepaper-success: "&7You've got a &5magic paper&7!"
  paper-name: "&5Magic&7-&5Paper"
  fix-not-able: "&7This item &ccannot &7be fixed."
  fix-already-fixed: "&7This item is &calready fixed&7."
  fix-fixed: "&7Your item has been &afixed&7."
  iteminfo-no-info-available: "&7Sorry, but there is &cno information &7about this item available."
  setowner-usage: "&7Please use &c/setowner <player>&7!"
  setowner-invalid-item: "&7Your item is &cinvalid&7!"
  setowner-disabled: "&7Owner bindings are on this server &cdisabled&7."
  setowner-no-owner: "&7Sorry, but you aren't the &cowner &7of this item!"
  setowner-set-owner: "&7Item owner has been set to &c%player&7."
  clearowner-reset: "&7The item owner has been &ccleared&7."
  levelup-message: "&7Your tool levelled up to level &c%level&7!"
actionbar:
  enable: true
  damage-increased: "&7Your damage has been &aincreased &7by &c%amount&7."
  damage-decreased: "&7Your damage taken has been &adecreased &7by &c%amount&7."
  more-mining-speed: "&7Your mining speed has been &aincreased &7by &c%amount&7."
console-command-milestones:
  '1': "say &c%player's &7LevellingTool reached level 1!"
lore-milestones:
  '1': "&7Noob-Level"
  '2': "&6Expert-Level"
  '3': "&bPro-Level"
  '4': "&5Dragonslayer-Level"
  '5': "&eGod-Level"