name: LevellingTools
author: Panischer
version: 1.0
api-version: 1.16
main: de.Panischer.LevellingTools.Main
commands:
   givepaper:
      description: /givepaper <player> <amount>
   configreload:
      description: /configreload
   fix:
      description: /fix
   iteminfo:
      description: /iteminfo
   setowner:
      description: /setowner <player>
   clearowner:
      description: /clearowner